#1 Sprint 9
Yuri-Yamaltdinov/java-filmorate pull request #2
Opened 2023-03-24 15:09 UTC by Yuri-Yamaltdinov

Первый pull request, реализация по ТЗ9 для ревью #1

2023-03-24 16:40 UTC, Yuri-Yamaltdinov commented
Pull request готов для ревью.

2023-03-25 17:31 UTC, TarasovSam requested changes
Юрий, привет!
Проверил твое задание, спасибо за работу. Все довольно хорошо. Особо хочу отметить, что мне понравилось, что ты проводишь логирование всех действий. Оставил комментарии с тем, что можно улучшить и что нужно поправить, плюс пару вопросов)
Жду твою работу на следующую итерацию!) Если будут вопросы, пиши в пачку)

2023-03-25 17:31 UTC, TarasovSam commented on pom.xml
> +	<description>Demo project for Spring Boot</description>
Обычно в описание пишут кратко назначение проекта.

2023-03-25 17:31 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private Map<Integer, Film> films = new HashMap<>();
Мапа будет меняться (заменяться) на другую мапу?)

2023-03-25 17:31 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        checkReleaseDate(film.getReleaseDate());
Так, ну смотри. Вот здесь можно поймать NPE. Думаю, что поймешь почему)
В строке 35 тоже.

2023-03-25 17:31 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private Set<String> userEmails = new HashSet<>();
Две ссылочные переменные будут заменяться?

2023-03-25 17:31 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getName() == null || user.getName().isEmpty() || user.getName().isBlank()) {
А какой смысл тройной проверки?

2023-03-25 17:31 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (!user.getBirthday().isBefore(LocalDate.now())) {
Для начала следует проверить значение на null, иначе есть шанс возникновения NPE.

2023-03-25 17:31 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getName() == null || user.getName().isEmpty() || user.getName().isBlank()) {
Здесь тоже тройная проверка)

2023-03-25 17:31 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (!user.getEmail().contains("@")) {
Для начала следует проверить значение на null, иначе есть шанс возникновения NPE.
А так же следует проверить на пустоту.

Но есть другой вопрос, в чем смысл ручной проверки, если ты прописываешь аннотации на поле?

2023-03-25 17:31 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotEmpty
В чем смысл трех аннотаций?
И в классе User тоже.

2023-03-26 10:49 UTC, Yuri-Yamaltdinov commented on pom.xml
> +	<description>Demo project for Spring Boot</description>
Подправил описание.

2023-03-26 10:51 UTC, Yuri-Yamaltdinov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private Map<Integer, Film> films = new HashMap<>();
Моя хроническая проблема с применением модификатора final. Ссылка на мапу не должна меняться, подправил, спасибо!)

2023-03-26 10:53 UTC, Yuri-Yamaltdinov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getName() == null || user.getName().isEmpty() || user.getName().isBlank()) {
Насколько понимаю метод isBlank заодно проверяет и на пустоту как isEmpty, т.е. можно оставить только проверку на null и на isBlank

2023-03-26 10:55 UTC, Yuri-Yamaltdinov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (!user.getBirthday().isBefore(LocalDate.now())) {
Т.к. в ТЗ не указано, что поле должно быть обязательным, то добавил проверку на пустоту и логирование, если поле отсутствует.

2023-03-26 10:57 UTC, Yuri-Yamaltdinov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotEmpty
Правильно понимаю, что можно оставить только NotNull и NotBlank?

2023-03-26 11:18 UTC, Yuri-Yamaltdinov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (!user.getEmail().contains("@")) {
Пришлось добавить ручные проверки продублировав аннотации из-за того, что не проходила проверка некоторых сценариев Постмана в GitHub Actions. При этом сценарии запущенные в Постмане локально проходили успешно.
Проверки случаев с аннотациями в GitHub стали проходить успешно после того, как заменил в pom.xml зависимость с hibernate.validation на spring-boot-starter validation

2023-03-26 11:25 UTC, Yuri-Yamaltdinov commented
Семён, привет! Спасибо большое за комментарии и наводки, которые, как всегда, провоцируют подтянуть теорию :-)
Удалил некоторые ручные проверки и соответствующие тесты, т.к. убедился, что проверки отрабатывают по аннотациями. 
Код готов для ревью №2.

2023-03-26 11:32 UTC, Yuri-Yamaltdinov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private Set<String> userEmails = new HashSet<>();
Поменял на final

2023-03-26 11:32 UTC, Yuri-Yamaltdinov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        checkReleaseDate(film.getReleaseDate());
Добавил проверку на Null и вывод в лог.

2023-03-26 11:33 UTC, Yuri-Yamaltdinov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getName() == null || user.getName().isEmpty() || user.getName().isBlank()) {
Оставил 2 проверки: на null и на isBlank

2023-03-26 16:04 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getName() == null || user.getName().isEmpty() || user.getName().isBlank()) {
Да, isBlank проверяет все тоже самое, что и isEmpty, но плюс к этому и на пустую строку из пробелов.

2023-03-26 16:06 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (!user.getBirthday().isBefore(LocalDate.now())) {
А тут нет противоречия с ТЗ, оно не обязательное)
Фишка в том, что если user.getBirthday()=null, то ты получишь NPE. Поэтому сначала проверяешь на null, а потом на isBefore.

2023-03-26 16:07 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (!user.getEmail().contains("@")) {
Пакет spring-boot-starter validation включает в себя hibernate.validation и еще кучу сверху)

2023-03-26 16:17 UTC, TarasovSam reviewed
Юрий, спасибо за то, что вносишь корректировки по рекомендациям. Оставил еще несколько комментариев, некоторые из них я настоятельно рекомендую принять к исполнению:)
Задание я принимаю, успеха в обучении и до следующего спринта!) Если будут вопросы, пиши в пачку.

PS для отступов можно использовать сочетание Ctrl+Alt+L для автоформатирования.

2023-03-26 16:17 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      @NotBlank
По сути можно оставить одну аннотацию, т.к. NotBlank проверяет на null) Для пользователя тоже самое (в двух местах).
На всякий:
isBlank(String str) checks if a String is whitespace, empty ("") or null.
StringUtils.isBlank(null)      = true  
StringUtils.isBlank("")        = true  
StringUtils.isBlank(" ")       = true  
StringUtils.isBlank("bob")     = false  
StringUtils.isBlank("  bob  ") = false  

isEmpty(String str) checks if a String is empty ("") or null.
StringUtils.isEmpty(null)      = true
StringUtils.isEmpty("")        = true
StringUtils.isEmpty(" ")       = false
StringUtils.isEmpty("bob")     = false
StringUtils.isEmpty("  bob  ") = false

2023-03-26 16:17 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (!user.getBirthday().isBefore(LocalDate.now())) {
Да не, немного по-другому)
Надо прописать в одном условии:
if (data.getBirthday() != null && data.getBirthday().isAfter(LocalDate.now())) {...}

2023-03-26 16:17 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      public Film postFilm(@NotNull @Valid @RequestBody Film film) {
Все довольно хорошо, но есть рекомендация - чтобы в каждом ендпоинте (методе контроллера) был только вызов соответствующего метода сервиса и еще дополнительно можно прописать логирование. Т.е. вся реализация уйдет в сервис. Так принято в разработке больших проектов.

2023-03-27 08:32 UTC, Yuri-Yamaltdinov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      @NotBlank
Оставил аннотацию NotBlank

2023-03-27 08:34 UTC, Yuri-Yamaltdinov commented
Выполнены доработки кода по результатам ревью №2.

2023-03-27 08:35 UTC, merged