Add friends likes
Yuri-Yamaltdinov/java-filmorate pull request #3
Opened 2023-04-15 10:21 UTC by Yuri-Yamaltdinov

Branch of TZ10 is ready for Pull Request

2023-04-15 19:15 UTC, TarasovSam requested changes
Юрий, привет!
Проверил твое задание, спасибо за работу. Оставил комментарии с тем, что можно улучшить и что нужно поправить, плюс пару вопросов)
Жду твою работу на следующую итерацию!) Если будут вопросы, пиши в пачку)

2023-04-15 19:15 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +public interface FilmStorage {
Методы для FilmStorage и UserStorage идентичны, поэтому их можно выделить в интерфейс с использованием дженериков.
Тоже самое можно сделать и для InMemoryStorage, но там несколько замороченнее)
Это рекомендация к рассмотрению.

2023-04-15 19:15 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    void checkReleaseDate(Film film);
Метод проверки, а так же методы по работе с лайками в Storage вносить не надо, здесь должны остаться только CRUD методы.

2023-04-15 19:15 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        userStorage.checkEmail(user);
В чем смысл этих проверок? И в следующем методе тоже?

2023-04-15 19:15 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorage.java
> +    void checkBirthday(User user);
Методы проверки, а так же методы по работе с друзьями в Storage вносить не надо, здесь должны остаться только CRUD методы.

2023-04-24 18:50 UTC, Yuri-Yamaltdinov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        userStorage.checkEmail(user);
метод CheckEmail проверяет, что при добавлении нового пользователя не существует пользователя с таким же email'ом

2023-04-24 18:51 UTC, Yuri-Yamaltdinov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +public class ErrorHandler {
Добавил логирование.

2023-04-24 19:57 UTC, Yuri-Yamaltdinov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +public interface FilmStorage {
Выделил отдельный метод Storage с использованием дженериков для FilmStorage и UserStorage

2023-04-24 19:58 UTC, Yuri-Yamaltdinov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        userStorage.checkEmail(user);
Пока делал метод Storage произвёл рефакторинг класса UserStorage, осознал почему не нужна проверка email в виде отдельного метода)

2023-04-25 13:18 UTC, TarasovSam reviewed
Юрий, проверил твое задание, спасибо за работу и за то, что дорабатываешь код) Оставил несколько дополнительных комментариев, посмотри их.
Задание я принимаю, успеха в обучении и до следующего спринта!) Если будут вопросы, пиши в пачку.

2023-04-25 13:18 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>      private String login;
Конечно для логина лучше прописать аннотацию @Pattern. Почитай про нее

2023-04-25 13:18 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (user.getName() == null || user.getName().isBlank()) {
Двойная проверка точно нужна?

2023-04-25 13:18 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/storage/Storage.java
> +public interface Storage<T> {
Да, отлично. Получили один универсальный интерфейс, который может быть использован для множества сущностей.
Но FilmStorage и UserStorage нужно вернуть. Эти классы будут просто экстендить интерфейс.

2023-05-07 09:43 UTC, merged